# Generated by Django 3.0.8 on 2022-01-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='ad',
        ),
    ]
