# Generated by Django 3.0.8 on 2022-01-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0003_auto_20220120_1314'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={},
        ),
    ]
