# Generated by Django 3.0.8 on 2022-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0004_auto_20220120_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='date',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Время создания'),
        ),
    ]
