# Generated by Django 3.0.8 on 2022-01-20 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0005_auto_20220120_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='date',
        ),
        migrations.AlterField(
            model_name='friend',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='app4.Rubric', verbose_name=' Рубрика'),
        ),
    ]
