# Generated by Django 3.0.8 on 2022-01-20 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app4', '0006_auto_20220120_1329'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friend',
            new_name='Announcement',
        ),
    ]
